config/routes.rb
Rails.application.routes.draw do


  resources :products, only: [:index]
  resource :cart
  resources :order_items, only: [:create, :update, :destroy]
  resources :pages
  get '/cart/show' => 'carts#show', as: :mycart
  post 'cart/update' => 'deliveries#new'
  get '/buildbox' => 'pages#index'
  get '/delivery' => 'pages#delivery'
  get '/confirmation' => 'pages#confirmation'
  # post '/cart' => 'carts#show', as: :mycart


  get 'pages/secret'
	root to: 'users#home'
	get 'users/new' => 'users#new', as: :new_user
	post 'users' => 'users#create'
  get '/users/account_profile' => 'users#account_profile', as: :account
  get '/pages/thanks' => 'pages#thanks'

  patch '/users/update' => 'users#update', as: :user

	# log in page with form:
	get '/login'     => 'sessions#new'

	# create (post) action for when log in form is submitted:
	post '/login'    => 'sessions#create'

	# delete action to log out:
	delete '/logout' => 'sessions#destroy'

  resources :charges
  get 'deliveries/new' => 'deliveries#new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attribute.rb
class Attribute < ApplicationRecord
  belongs_to :product
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  belongs_to :order_status, foreign_key: :status
  has_many :order_items
  before_save :update_subtotal

  def subtotal
   order_items.collect { |oi| oi.valid? ? (oi.orderitems_quantity * oi.unit_price) : 0 }.sum
  end

  def update_subtotal
    p "subtotal == ", self[:subtotal] = subtotal
  end

  def cart_total
    self[:total_price] = self[:orderitems_quantity] * self[:unit_price]
   order_items.to_a.sum { |item| item.total_price }
 end

private

  def update_subtotal
    self[:subtotal] = subtotal
  end
end

app/models/order_item.rb
class OrderItem < ActiveRecord::Base
  belongs_to :product
  belongs_to :order

  validates :orderitems_quantity, presence: true, numericality: { only_integer: true, greater_than: 0 }
  validate :product_present
  validate :order_present

  before_save :finalize

  def unit_price
    if persisted?
      self[:unit_price]
    else
      product.product_price
    end
  end

private
  def product_present
    if product.nil?
      errors.add(:product, "is not valid or is not active.")
    end
  end

  def order_present
    if order.nil?
      errors.add(:order, "is not a valid order.")
    end
  end

  def finalize
    self[:unit_price] = unit_price
    self[:total_price] = self[:orderitems_quantity] * self[:unit_price]
  end
end

app/models/order_status.rb
class OrderStatus < ApplicationRecord

  has_many :orders

  def self.in_progress
    @in_progress ||= find_by(name: 'In Progress')
  end

end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :order_items, dependent: :destroy


end

app/models/user.rb
class User < ApplicationRecord
  has_many :orders
  has_secure_password
  validates :email, :phone_number, presence: true, uniqueness: true
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

  def show
    @sub = current_order.subtotal * 100
    @order_items = current_order.order_items
    @order = current_order
    @amount = @sub/100.00 + params[:fee].to_i/100.00
    @fee = params[:fee].to_i
    current_order.update(tax: @fee.to_f)
    render :show, locals: {fee: @fee}
  end

  def create
    customer = Stripe::Customer.create(
      :email => params[:stripeEmail]
    )

    charge = Stripe::Charge.create(
      :customer    => customer.id,
      :amount      => @amount,
      :description => 'Rails Stripe customer',
      :currency    => 'usd'
    )

  rescue Stripe::CardError => e
    flash[:error] = e.message
    render 'create'
  end


  private

  def deliver_params
    p params
    params.permit(:street_address)
  end

end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  FROM  = "1 washington avenue, Miami Beach, FL"

  def new
    @amount = current_order.subtotal * 100 #+ @quote.fee

    package = {
                :manifest => "a box of kittens",
                :pickup_name => "The Warehouse",
                :pickup_address => "1 Ocean Drive, Miami Beach, FL",
                :pickup_phone_number => "415-555-1234",
                # :pickup_business_name => "Optional Pickup Business Name, Inc.",
                :pickup_notes => "Optional note that this is Invoice #123",
                :dropoff_name => "Alice",
                :dropoff_address => "1 washington avenue, Miami Beach, FL, FL",
                :dropoff_phone_number => "415-555-1234", # params[:drop_phone]
                # :dropoff_business_name => "Optional Dropoff Business Name, Inc.",
                :dropoff_notes => "Optional note to ring the bell",
                # :quote_id => @quote.id #"dqt_K9LFfpSZCdAJsk"
              }

      @delivery = $client.create(package)

  end

  def create

    customer = Stripe::Customer.create(
      :email => params[:stripeEmail]
    )

    charge = Stripe::Charge.create(
      :customer    => customer.id,
      :amount      => @amount,
      :description => 'Rails Stripe customer',
      :currency    => 'usd'
    )


    redirect_to root_path

  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to new_charge_path
  end

  def thanks
  end

  def show
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :authorize, only: [:secret]

  def show
    @order_items = current_order.order_items
  end

  def buildbox
    def create
      @order = current_order
      @order.status = OrderStatus.in_progress.id
      @order_item = @order.order_items.new(order_item_params)
      @order.save
      session[:order_id] = @order.id
    end

    def show
    end

    def update
      @order = current_order
      @order_item = @order.order_items.find(params[:id])
      @order_item.update_attribute(:orderitems_quantity, order_item_params[:orderitems_quantity])
    end

  end

  def index
    @products = Product.all
    @order_item = current_order.order_items.new
  end
  private



  def order_item_params
    params.require(:order_item).permit(:orderitems_quantity, :product_id)
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def index
    @products = Product.all
    @order_item = current_order.order_items.new
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    puts user_params
    @user = User.new(user_params)
    puts @user
    @user.email.downcase!

    if @user.save
      flash[:notice] = "Account created successfully!"
      redirect_to login_path
    else
      flash.now.alert = "Oops, couldn't create account. Please make sure you are using a valid email and password and try again."
      render :new
    end
  end

  def home
  end

  def account_profile
    @user = current_user
  end

  def update
    @user = User.find(params[:id])
    puts @user
    if @user.update(user_params)
      redirect_to account_path
    else
      render :edit
    end
  end

private

  def user_params
    params.require(:user).permit(:id, :first_name, :last_name, :phone_number, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attributes_helper.rb
module AttributesHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/deliveries_helper.rb
module DeliveriesHelper
end

app/helpers/git_helper.rb
module GitHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/products/_product_row.html.erb
<div class="well">

  <div class="row">
    <div class="col-xs-8">
      <h4><%= product.product_name %></small></h4>
    </div>
    <div class="col-xs-4">

      <%= form_for order_item, remote: true do |f| %>
      <h4 class="text-right">Unit Price: <span style="color: green"><%= number_to_currency product.product_price %></span></h4>
        <div class="input-group">
          <%= f.number_field :orderitems_quantity, value: 1, class: "form-control", min: 1 %>
          <div class="input-group-btn">
            <%= f.hidden_field :product_id, value: product.id %>
            <%= f.submit "Add to Cart", class: "btn btn-warning" %>
          </div>
        </div>
      <% end %>
    </div>

  </div>
</div>

app/views/products/index.html.erb
<h3 class="text-center">Products for Sale</h3>

<div class="row">
  <div class="col-xs-6 col-xs-offset-3">
    <% @products.each do |product| %>
      <%= render "product_row", product: product, order_item: @order_item %>
    <% end %>
  </div>
</div>

app/views/products/new.html.erb
<h1>Create Product</h1>
<%= form_for @product do |f| %>
  <div>
    <%= f.label :product_name %>
    <%= f.text_field :product_name %>
  </div>
  <div>
    <%= f.label :product_quantity %>
    <%= f.text_field :product_quantity %>
  </div>
  <div>
    <%= f.label :product_weight%>
    <%= f.text_field :product_weight %>
  </div>
  <div>
    <%= f.label :product_dimension %>
    <%= f.text_field :product_dimension %>
  </div>
  <div>
    <%= f.label :product_description %>
    <%= f.text_field :product_description %>
  </div>
  <div>
    <%= f.label :product_image_url %>
    <%= f.text_field :product_image_url %>
  </div>
  <div>
    <%= f.label :product_group %>
    <%= f.text_field :product_group %>
  </div>
  <div>
    <%= f.label :product_price %>
    <%= f.text_field :product_price %>
  </div>

  <div>
    <%= f.submit "Done" %>
  </div>
<% end %>

app/views/users/_contact_form.html.erb
<section class="section">
  <div class="section-cover"></div>

  <!--Section heading-->
  <div class="container3">
    <h2 class="section-heading h1 pt-4">CONTACT US</h2>
    <!--Section description-->
    <p class="section-description">Want to chat? Don't hesitate to reach out and our team will get back to you within 24 hours!</p>

    <div class="row">

      <!--Grid column-->
      <div class="col-md-8 col-xl-9">
        <form id="contact-form" name="contact-form" action="mail.php" method="POST">

          <!--Grid row-->
          <div class="row">

            <!--Grid column-->
            <div class="col-md-6">
              <div class="md-form">
                <input type="text" id="name" name="name" class="form-control">
                <label for="name" class="">Your name</label>
              </div>
            </div>
            <!--Grid column-->

            <!--Grid column-->
            <div class="col-md-6">
              <div class="md-form">
                <input type="text" id="email" name="email" class="form-control">
                <label for="email" class="">Your email</label>
              </div>
            </div>
            <!--Grid column-->

          </div>
          <!--Grid row-->

          <!--Grid row-->
          <div class="row">
            <div class="col-md-12">
              <div class="md-form">
                <input type="text" id="subject" name="subject" class="form-control">
                <label for="subject" class="">Subject</label>
              </div>
            </div>
          </div>
          <!--Grid row-->

          <!--Grid row-->
          <div class="row">

            <!--Grid column-->
            <div class="col-md-12">

              <div class="md-form">
                <textarea type="text" id="message" name="message" rows="2" class="form-control md-textarea"></textarea>
                <label for="message">Your message</label>
              </div>

            </div>
          </div>
          <!--Grid row-->

        </form>

        <div class="center-on-small-only">
          <a class="btn btn-outline-light" onclick="document.getElementById('contact-form').submit();">Send</a>
        </div>
        <!--Grid column-->

      </div>
    </div>
  </section>

app/views/users/_customer_review.html.erb
<section class="team-section text-center my-5">

  <!-- Section heading -->
  <h2 class="h1-responsive font-weight-bold my-5">Customer Reviews</h2>
  <!-- Section description -->
  <p class="dark-grey-text w-responsive mx-auto mb-5"></p>

  <!--Grid row-->
  <div class="row text-center">

    <!--Grid column-->
    <div class="col-md-4 mb-md-0 mb-5">

      <div class="testimonial">
        <!--Avatar-->
        <div class="avatar mx-auto">
          <img src="https://mdbootstrap.com/img/Photos/Avatars/img%20(1).jpg" class="rounded-circle z-depth-1 img-fluid">
        </div>
        <!--Content-->
        <h4 class="font-weight-bold dark-grey-text mt-4">Bria Gay-Mitchell</h4>
        <h6 class="font-weight-bold blue-text my-3">Beach-Goer</h6>
        <p class="font-weight-normal dark-grey-text">
          <i class="fa fa-quote-left pr-2"></i>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quod eos id officiis hic tenetur quae quaerat ad velit ab hic tenetur.</p>
        <!--Review-->
        <div class="orange-text">
          <i class="fa fa-star"> </i>
          <i class="fa fa-star"> </i>
          <i class="fa fa-star"> </i>
          <i class="fa fa-star"> </i>
          <i class="fa fa-star-half-full"> </i>
        </div>
      </div>

    </div>
    <!--Grid column-->

    <!--Grid column-->
    <div class="col-md-4 mb-md-0 mb-5">

      <div class="testimonial">
        <!--Avatar-->
        <div class="avatar mx-auto">
          <img src="https://mdbootstrap.com/img/Photos/Avatars/img%20(8).jpg" class="rounded-circle z-depth-1 img-fluid">
        </div>
        <!--Content-->
        <h4 class="font-weight-bold dark-grey-text mt-4">Ed Toro</h4>
        <h6 class="font-weight-bold blue-text my-3">Family Man</h6>
        <p class="font-weight-normal dark-grey-text">
          <i class="fa fa-quote-left pr-2"></i>Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid commodi.</p>
        <!--Review-->
        <div class="orange-text">
          <i class="fa fa-star"> </i>
          <i class="fa fa-star"> </i>
          <i class="fa fa-star"> </i>
          <i class="fa fa-star"> </i>
          <i class="fa fa-star"> </i>
        </div>
      </div>

    </div>
    <!--Grid column-->

    <!--Grid column-->
    <div class="col-md-4">

      <div class="testimonial">
        <!--Avatar-->
        <div class="avatar mx-auto">
          <img src="https://mdbootstrap.com/img/Photos/Avatars/img%20(10).jpg" class="rounded-circle z-depth-1 img-fluid">
        </div>
        <!--Content-->
        <h4 class="font-weight-bold dark-grey-text mt-4">Jo Mikkola</h4>
        <h6 class="font-weight-bold blue-text my-3">Mom & Wife</h6>
        <p class="font-weight-normal dark-grey-text">
          <i class="fa fa-quote-left pr-2"></i>At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti.</p>
        <!--Review-->
        <div class="orange-text">
          <i class="fa fa-star"> </i>
          <i class="fa fa-star"> </i>
          <i class="fa fa-star"> </i>
          <i class="fa fa-star"> </i>
          <i class="fa fa-star-o"> </i>
        </div>
      </div>

    </div>
    <!--Grid column-->

  </div>
  <!--Grid row-->

</section>
<!-- Section: Testimonials v.3 -->

app/views/users/_footer.html.erb
<footer class="page-footer">

<div class="footer">

  <div class="footer-logo">
    <%= image_tag "logosmallwhite.png", width: "800", height: "auto", alt: "logo" %>
  </div>
  <p></p>
<h6>© 2018 Copyright: BeachBox</h6>
</div>

</footer>

app/views/users/_login.html.erb
<div id="login-modal1">
  <%= form_tag '/login' do %>
    <div>
      <%= label_tag :email, "Email:" %><br>
      <%= text_field_tag :email, nil, autofocus: true %>
    </div>

    <div>
      <%= label_tag :password, "Password:" %><br>
      <%= password_field_tag :password%>
    </div>

    <br>

    <div>
      <%= submit_tag "Log In", class: "btn btn-outline-warning" %>
    </div>
  <% end %>
</div>

app/views/users/_login_modal.html.erb
<div class="modal fade" id="LoginModal" tabindex="-1" role="dialog" aria-labelledby="LoginModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="LoginModalLabel">
          <%= image_tag "logosmall.png", width:200, height:"auto", alt:"beach box logo"  %>
        </h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= render partial: 'users/login' %>
      </div>
    </div>
  </div>
</div>

app/views/users/_login_signup_modal.html.erb
<div class="modal fade" id="myModal1" tabindex="-1" role="dialog" aria-labelledby="myModal1Label" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">

        <h5 class="modal-title" id="myModal1Label">
          <%= image_tag "logosmall.png", width:200, height:"auto", alt:"beach box logo"  %>
        </h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>

      </div>
      <div class="modal-body">
        <div role="tabpanel">
          <!-- Nav tabs -->
          <ul class="nav nav-pills nav-fill">
            <li class="nav-item"><a href="#uploadTab" aria-controls="uploadTab" role="tab" data-toggle="tab">Login</a>
            </li>
            <li class="nav-item"><a href="#browseTab" aria-controls="browseTab" role="tab" data-toggle="tab">Register</a>
            </li>
          </ul>
          <!-- Tab panes -->
          <div class="tab-content">
            <div role="tabpanel" class="tab-pane active" id="uploadTab">
             <%= render partial: 'users/login' %>
            </div>
            <div role="tabpanel" class="tab-pane" id="browseTab">
             <%= render partial: 'users/signup' %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/_register_modal.html.erb
<div class="modal fade" id="RegisterModal" tabindex="-1" role="dialog" aria-labelledby="RegisterModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="RegisterModalLabel">
          <%= image_tag "logosmall.png", width:200, height:"auto", alt:"beach box logo"  %>
        </h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= render partial: 'users/signup' %>
      </div>
    </div>
  </div>
</div>

app/views/users/_signup.html.erb
<div id="signup-modal1">
  <% @user = User.new %>
  <%= form_for @user, url: users_path, method: 'POST' do |f| %>
    <div>
      <%= f.label :first_name, "First Name:" %><br>
      <%= f.text_field :first_name, autofocus: true %></div>

    <div>
      <%= f.label :email, "Email:" %><br>
      <%= f.text_field :email %>
    </div>

    <div>
      <%= f.label :phone_number, "Phone Number:" %><br>
      <%= f.text_field :phone_number %>
    </div>

    <div>
      <%= f.label :password, "Password:" %><br>
      <%= f.password_field :password %>
    </div>

    <div>
      <%= f.label :password_confirmation, "Confirm Password:" %><br>
      <%= f.password_field :password_confirmation %>
    </div>

    <br>

    <div>
      <%= f.submit "Sign up!", class: "btn btn-outline-warning" %>
    </div>
  <% end %>
</div>

app/views/users/account_profile.html.erb
<h1>USER PROFILE</h1>
<div id="container6">
  <% @user = current_user %>
  <%= form_for @user, url: user_path(:id => current_user.id), method: 'PATCH' do |f| %>

  <div>
    <%= f.label :first_name, "First Name:", class: "col-sm-2" %>
    <%= f.text_field :first_name, class: "col-sm-4" %>
  </div>
  <div>
    <%= f.label :email, "Email: ", class: "col-sm-2" %>
    <%= f.text_field :email, class: "col-sm-4" %>
  </div>
  <div>
    <%= f.label :phone_number, "Phone Number: ", class: "col-sm-2" %>
    <%= f.text_field :phone_number, class: "col-sm-4" %>    
  </div>
  <div>
    <%= f.label :password, "Update Your Password: ", class: "col-sm-2" %>
    <%= f.password_field :password, class: "col-sm-4" %>
  </div>
  <div>
    <%= f.label :password_confirmation, "Confirm Password Update: ", class: "col-sm-2" %>
    <%= f.password_field :password_confirmation, class: "col-sm-4" %>
  </div>
  <p></p>
  <div class="button6">
    <%= f.submit "Update!", class: "btn btn-warning" %>
  </div>
<% end %>
</div>

app/views/users/home.html.erb
<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <div class="display-4"><%= image_tag "logosmall.png", width:200, height:"auto", alt:"beach box logo"  %></div>
    <div class=""><h2>This could be you.</h2></div>
  </div>
</div>

<!-- BUILD A BOX BUTTON // LOGIN  // REGISTER -->

<div class=container1>
  <% if current_user %>
    <%= link_to 'Build-A-BeachBox', buildbox_path, class: "btn btn-outline-light btn-lg" %>
  <% else %>
  <button type="button" class="btn btn-outline-light btn-lg" data-toggle="modal" data-target="#myModal1">
  Build-A-BeachBox
  </button>
  <% end %>
</div>

<%= render partial: "users/login_signup_modal" %>

<!-- CUSTOMER REVIEW -->

<%= render partial: "users/customer_review" %>

<!-- CONTACT US FORM -->

<%= render partial: "users/contact_form" %>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for @user do |f| %>
  <div>
    <%= f.label :first_name %>
    <%= f.text_field :first_name, autofocus: true %>
  </div>
  <div>
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>
  <div>
    <%= f.label :phone_number %>
    <%= f.text_field :phone_number %>    
  </div>
  <div>
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>
  <div>
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </div>
  <div>
    <%= f.submit "Sign up!" %>
  </div>
<% end %>