config/routes.rb
Rails.application.routes.draw do


  resources :products, only: [:index]
  resource :cart
  resources :order_items, only: [:create, :update, :destroy]
  resources :pages
  get '/cart/show' => 'carts#show', as: :mycart
  post 'cart/update' => 'deliveries#new'
  get '/buildbox' => 'pages#index'
  get '/delivery' => 'pages#delivery'
  get '/confirmation' => 'pages#confirmation'
  # post '/cart' => 'carts#show', as: :mycart


  get 'pages/secret'
	root to: 'users#home'
	get 'users/new' => 'users#new', as: :new_user
	post 'users' => 'users#create'
  get '/users/account_profile' => 'users#account_profile', as: :account
  get '/pages/thanks' => 'pages#thanks'

  patch '/users/update' => 'users#update', as: :user

	# log in page with form:
	get '/login'     => 'sessions#new'

	# create (post) action for when log in form is submitted:
	post '/login'    => 'sessions#create'

	# delete action to log out:
	delete '/logout' => 'sessions#destroy'

  resources :charges
  get 'deliveries/new' => 'deliveries#new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attribute.rb
class Attribute < ApplicationRecord
  belongs_to :product
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  belongs_to :order_status, foreign_key: :status
  has_many :order_items
  before_save :update_subtotal

  def subtotal
   order_items.collect { |oi| oi.valid? ? (oi.orderitems_quantity * oi.unit_price) : 0 }.sum
  end

  def update_subtotal
    p "subtotal == ", self[:subtotal] = subtotal
  end

  def cart_total
    self[:total_price] = self[:orderitems_quantity] * self[:unit_price]
   order_items.to_a.sum { |item| item.total_price }
 end

private

  def update_subtotal
    self[:subtotal] = subtotal
  end
end

app/models/order_item.rb
class OrderItem < ActiveRecord::Base
  belongs_to :product
  belongs_to :order

  validates :orderitems_quantity, presence: true, numericality: { only_integer: true, greater_than: 0 }
  validate :product_present
  validate :order_present

  before_save :finalize

  def unit_price
    if persisted?
      self[:unit_price]
    else
      product.product_price
    end
  end

private
  def product_present
    if product.nil?
      errors.add(:product, "is not valid or is not active.")
    end
  end

  def order_present
    if order.nil?
      errors.add(:order, "is not a valid order.")
    end
  end

  def finalize
    self[:unit_price] = unit_price
    self[:total_price] = self[:orderitems_quantity] * self[:unit_price]
  end
end

app/models/order_status.rb
class OrderStatus < ApplicationRecord

  has_many :orders

  def self.in_progress
    @in_progress ||= find_by(name: 'In Progress')
  end

end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :order_items, dependent: :destroy


end

app/models/user.rb
class User < ApplicationRecord
  has_many :orders
  has_secure_password
  validates :email, :phone_number, presence: true, uniqueness: true
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

  def show
    @sub = current_order.subtotal * 100
    @order_items = current_order.order_items
    @order = current_order
    @amount = @sub/100.00 + params[:fee].to_i/100.00
    @fee = params[:fee].to_i
    current_order.update(tax: @fee.to_f)
    render :show, locals: {fee: @fee}
  end

  def create
    customer = Stripe::Customer.create(
      :email => params[:stripeEmail]
    )

    charge = Stripe::Charge.create(
      :customer    => customer.id,
      :amount      => @amount,
      :description => 'Rails Stripe customer',
      :currency    => 'usd'
    )

  rescue Stripe::CardError => e
    flash[:error] = e.message
    render 'create'
  end


  private

  def deliver_params
    p params
    params.permit(:street_address)
  end

end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  FROM  = "1 washington avenue, Miami Beach, FL"

  def new
    @amount = current_order.subtotal * 100 #+ @quote.fee

    package = {
                :manifest => "a box of kittens",
                :pickup_name => "The Warehouse",
                :pickup_address => "1 Ocean Drive, Miami Beach, FL",
                :pickup_phone_number => "415-555-1234",
                # :pickup_business_name => "Optional Pickup Business Name, Inc.",
                :pickup_notes => "Optional note that this is Invoice #123",
                :dropoff_name => "Alice",
                :dropoff_address => "1 washington avenue, Miami Beach, FL, FL",
                :dropoff_phone_number => "415-555-1234", # params[:drop_phone]
                # :dropoff_business_name => "Optional Dropoff Business Name, Inc.",
                :dropoff_notes => "Optional note to ring the bell",
                # :quote_id => @quote.id #"dqt_K9LFfpSZCdAJsk"
              }

      @delivery = $client.create(package)

  end

  def create

    customer = Stripe::Customer.create(
      :email => params[:stripeEmail]
    )

    charge = Stripe::Charge.create(
      :customer    => customer.id,
      :amount      => @amount,
      :description => 'Rails Stripe customer',
      :currency    => 'usd'
    )


    redirect_to root_path

  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to new_charge_path
  end

  def thanks
  end

  def show
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :authorize, only: [:secret]

  def show
    @order_items = current_order.order_items
  end

  def buildbox
    def create
      @order = current_order
      @order.status = OrderStatus.in_progress.id
      @order_item = @order.order_items.new(order_item_params)
      @order.save
      session[:order_id] = @order.id
    end

    def show
    end

    def update
      @order = current_order
      @order_item = @order.order_items.find(params[:id])
      @order_item.update_attribute(:orderitems_quantity, order_item_params[:orderitems_quantity])
    end

  end

  def index
    @products = Product.all
    @order_item = current_order.order_items.new
  end
  private



  def order_item_params
    params.require(:order_item).permit(:orderitems_quantity, :product_id)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    puts user_params
    @user = User.new(user_params)
    puts @user
    @user.email.downcase!

    if @user.save
      flash[:notice] = "Account created successfully!"
      redirect_to login_path
    else
      flash.now.alert = "Oops, couldn't create account. Please make sure you are using a valid email and password and try again."
      render :new
    end
  end

  def home
  end

  def account_profile
    @user = current_user
  end

  def update
    @user = User.find(params[:id])
    puts @user
    if @user.update(user_params)
      redirect_to account_path
    else
      render :edit
    end
  end

private

  def user_params
    params.require(:user).permit(:id, :first_name, :last_name, :phone_number, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attributes_helper.rb
module AttributesHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/deliveries_helper.rb
module DeliveriesHelper
end

app/helpers/git_helper.rb
module GitHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/attributes/_form.html.haml
= form_for @attribute do |f|
  - if @attribute.errors.any?
    #error_explanation
      %h2= "#{pluralize(@attribute.errors.count, "error")} prohibited this attribute from being saved:"
      %ul
        - @attribute.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :product
    = f.text_field :product
  .actions
    = f.submit 'Save'

app/views/attributes/edit.html.haml
%h1 Editing attribute

= render 'form'

= link_to 'Show', @attribute
\|
= link_to 'Back', attributes_path

app/views/attributes/index.html.haml
%h1 Listing attributes

%table
  %thead
    %tr
      %th Product
      %th
      %th
      %th

  %tbody
    - @attributes.each do |attribute|
      %tr
        %td= attribute.product
        %td= link_to 'Show', attribute
        %td= link_to 'Edit', edit_attribute_path(attribute)
        %td= link_to 'Destroy', attribute, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Attribute', new_attribute_path

app/views/attributes/new.html.haml
%h1 New attribute

= render 'form'

= link_to 'Back', attributes_path

app/views/attributes/show.html.haml
%p#notice= notice

%p
  %b Product:
  = @attribute.product

= link_to 'Edit', edit_attribute_path(@attribute)
\|
= link_to 'Back', attributes_path

app/views/carts/_cart_row.html.erb
<div id="cart-show-page">
  <div class="container">
    <div class="row">
      <div class="col-sm">

        <%= form_for order_item, remote: true do |f| %>

        <h4><%= product.product_name %></h4>

        <div>Unit Price: <span style="color: green"><%= number_to_currency order_item.unit_price %></span></div>


      </div>
      <div class="col-sm-1" id="order-count">

        <%= f.number_field :orderitems_quantity, value: order_item.orderitems_quantity.to_i, class: "form-control number qty", min: 0 %>
        <%= f.hidden_field :product_id, value: product.id %>

      </div>
      <div class="col-sm">


        <%= f.submit "Update", class: "btn btn-info btn-md"%>
        <%= link_to(
          "Delete",
          order_item,
          method: :delete,
          action: :remove,
          remote: true,
          data: { confirm: 'Are you sure?'},
          class: "btn btn-danger btn-md",
            id: "danger"
            ) %>

            <div>
              <p class="subtotal">Total Price: <span style="color: green"><%= number_to_currency order_item.total_price %></span></p>
            </div>

          </div>
        </div>
      </div>


      <% end %>
    </div>

app/views/carts/_shopping_cart.html.erb
<div>
  <% if !@order_item.nil? && @order_item.errors.any? %>
  <div class="alert alert-danger">
    <ul>
      <% @order_item.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
  <% end %>
  <% if @order_items.size == 0 %>
  <p class="text-center">
    There are no items in your shopping cart. Please <%= link_to "go back", '/buildbox' %> and add some items to your cart.
  </p>
  <% else %>
  <% @order_items.each do |order_item| %>
  <%= render 'carts/cart_row', product: order_item.product, order_item: order_item, show_total: true %>
  <% end %>
  <% end %>
</div>

app/views/carts/create.html.erb
<div class="thank-you jumbotron-fluid">
  <div>
    <div class="">
      <p>
        <h1>Just a quick thank you for your payment!</h1>
      </p>
      <p>
        <h2>
          Your Postmates driver will be arriving shortly.
        </h2>
      </p>
      <p></p>
      <div class="thank-you-btn">        
        <img src="assets/postmatesdelivery.png" alt="logo"><br>
        <%= link_to 'Home', root_path, class: 'btn btn-outline-info' %>
      </div>
    </div>
  </div>
</div>

app/views/carts/new.html.erb
<!--
<%= form_tag charges_path do %>
  <article>
    <% if flash[:error].present? %>
      <div id="error_explanation">
        <p><%= flash[:error] %></p>
      </div>
    <% end %>
    <label class="amount">
      <span>Your Beach Box will cost you: $</span> <%= @amount/100.00 %>
    </label>

    <p>Your estimated delivery cost is $ <%= @delivery.fee/100.00 %> </p>
            <p> <%= @delivery.dropoff_eta %> </p>



  </article>

  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="A month's subscription"
          data-amount="<%= @amount %>"
          data-bitcoin="true"
          data-locale="auto"></script>
<% end %>
<%= console %> -->

app/views/carts/show.html.erb
<div class="stepper">

  <div class="stepper-step stepper-step-isValid">
    <div class="stepper-stepContent">
      <span class="stepper-stepMarker">1</span>Build Your Box
    </div>
  </div>
  <div class="stepper-step stepper-step-isActive">
    <div class="stepper-stepContent">
      <span class="stepper-stepMarker">2</span>Delivery
    </div>
  </div>
  <div class="stepper-step stepper-step-isActive">
    <div class="stepper-stepContent">
      <span class="stepper-stepMarker">3</span>Checkout
    </div>
  </div>
</div>
<h1>Review & Checkout</h1>
<br>
<%= render "shopping_cart" %>

<div id="cart-show-page1">
  <%= form_tag cart_path do %>
  <article>
    <% if flash[:error].present? %>
    <div id="error_explanation">
      <p><%= flash[:error] %></p>
    </div>
    <% end %>
    <label class="amount">
      <span><strong>Your Beach Box will cost you:</strong> $</span><%=@amount%>
    </label>
    <p><strong>Subtotal:</strong> $<%= @sub/100.00  %></p>
    <p><strong>Your estimated delivery cost is:</strong> $<%= @fee/100.00 %> </p>
  </article>

  <p></p>
  <%= link_to '<button type="button" class="btn btn-warning">Back</button>'.html_safe, '/delivery' %>
  <p></p>

  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
  data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
  data-description="Beach Box"
  data-amount="<%= @amount*100 %>"
  data-locale="auto"></script>
  
  <% end %>

</div>

app/views/charges/new.html.erb
<%= form_tag charges_path do %>
  <article>
    <% if flash[:error].present? %>
      <div id="error_explanation">
        <p><%= flash[:error] %></p>
      </div>
    <% end %>
    <label class="amount">
      <span>Your Beach Box will cost you: $</span> <%= @amount/100.00 %>
    </label>

    <p>Your estimated delivery cost is $ <%= @delivery.fee/100.00 %> </p>
            <p> <%= @delivery.dropoff_eta %> </p>



  </article>

  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="A month's subscription"
          data-amount="<%= @amount %>"
          data-bitcoin="true"
          data-locale="auto"></script>
<% end %>
<%= console %>