config/routes.rb
Rails.application.routes.draw do


  resources :products, only: [:index]
  resource :cart
  resources :order_items, only: [:create, :update, :destroy]
  resources :pages
  get '/cart/show' => 'carts#show', as: :mycart
  post 'cart/update' => 'deliveries#new'
  get '/buildbox' => 'pages#index'
  get '/delivery' => 'pages#delivery'
  get '/confirmation' => 'pages#confirmation'
  # post '/cart' => 'carts#show', as: :mycart


  get 'pages/secret'
	root to: 'users#home'
	get 'users/new' => 'users#new', as: :new_user
	post 'users' => 'users#create'
  get '/users/account_profile' => 'users#account_profile', as: :account
  get '/pages/thanks' => 'pages#thanks'

  patch '/users/update' => 'users#update', as: :user

	# log in page with form:
	get '/login'     => 'sessions#new'

	# create (post) action for when log in form is submitted:
	post '/login'    => 'sessions#create'

	# delete action to log out:
	delete '/logout' => 'sessions#destroy'

  resources :charges
  get 'deliveries/new' => 'deliveries#new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attribute.rb
class Attribute < ApplicationRecord
  belongs_to :product
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  belongs_to :order_status, foreign_key: :status
  has_many :order_items
  before_save :update_subtotal

  def subtotal
   order_items.collect { |oi| oi.valid? ? (oi.orderitems_quantity * oi.unit_price) : 0 }.sum
  end

  def update_subtotal
    p "subtotal == ", self[:subtotal] = subtotal
  end

  def cart_total
    self[:total_price] = self[:orderitems_quantity] * self[:unit_price]
   order_items.to_a.sum { |item| item.total_price }
 end

private

  def update_subtotal
    self[:subtotal] = subtotal
  end
end

app/models/order_item.rb
class OrderItem < ActiveRecord::Base
  belongs_to :product
  belongs_to :order

  validates :orderitems_quantity, presence: true, numericality: { only_integer: true, greater_than: 0 }
  validate :product_present
  validate :order_present

  before_save :finalize

  def unit_price
    if persisted?
      self[:unit_price]
    else
      product.product_price
    end
  end

private
  def product_present
    if product.nil?
      errors.add(:product, "is not valid or is not active.")
    end
  end

  def order_present
    if order.nil?
      errors.add(:order, "is not a valid order.")
    end
  end

  def finalize
    self[:unit_price] = unit_price
    self[:total_price] = self[:orderitems_quantity] * self[:unit_price]
  end
end

app/models/order_status.rb
class OrderStatus < ApplicationRecord

  has_many :orders

  def self.in_progress
    @in_progress ||= find_by(name: 'In Progress')
  end

end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :order_items, dependent: :destroy


end

app/models/user.rb
class User < ApplicationRecord
  has_many :orders
  has_secure_password
  validates :email, :phone_number, presence: true, uniqueness: true
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

  def show
    @sub = current_order.subtotal * 100
    @order_items = current_order.order_items
    @order = current_order
    @amount = @sub/100.00 + params[:fee].to_i/100.00
    @fee = params[:fee].to_i
    current_order.update(tax: @fee.to_f)
    render :show, locals: {fee: @fee}
  end

  def create
    customer = Stripe::Customer.create(
      :email => params[:stripeEmail]
    )

    charge = Stripe::Charge.create(
      :customer    => customer.id,
      :amount      => @amount,
      :description => 'Rails Stripe customer',
      :currency    => 'usd'
    )

  rescue Stripe::CardError => e
    flash[:error] = e.message
    render 'create'
  end


  private

  def deliver_params
    p params
    params.permit(:street_address)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :authorize, only: [:secret]

  def show
    @order_items = current_order.order_items
  end

  def buildbox
    def create
      @order = current_order
      @order.status = OrderStatus.in_progress.id
      @order_item = @order.order_items.new(order_item_params)
      @order.save
      session[:order_id] = @order.id
    end

    def show
    end

    def update
      @order = current_order
      @order_item = @order.order_items.find(params[:id])
      @order_item.update_attribute(:orderitems_quantity, order_item_params[:orderitems_quantity])
    end

  end

  def index
    @products = Product.all
    @order_item = current_order.order_items.new
  end
  private



  def order_item_params
    params.require(:order_item).permit(:orderitems_quantity, :product_id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attributes_helper.rb
module AttributesHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/deliveries_helper.rb
module DeliveriesHelper
end

app/helpers/git_helper.rb
module GitHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_cart_text.html.erb
<%= link_to "#{current_order.order_items.size} Items in Cart ( #{number_to_currency current_order.subtotal} )", cart_path, class: "btn btn-link" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Beachbox</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <script src="https://code.jquery.com/jquery-1.11.1.min.js"></script>
  <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js" integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js" integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm" crossorigin="anonymous"></script>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <script src="https://maps.googleapis.com/maps/api/js?key=<%=Rails.application.credentials.dig(:google_map, :api_key)%>&callback=initMap"></script>

  <%= favicon_link_tag asset_path('favicon.png'), :rel => 'icon', :type =>  'image/png' %>

</head>

<body>


  <!-- NAVIGATION BAR -->


  <nav class="navbar navbar-expand-lg navbar-light bg-white; ">

    <a class="navbar-brand" href="/">
      <%= image_tag "logosmall.png", width:200, height:"auto", alt:"beach box logo"  %>
    </a>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="navbar-nav ml-auto">
        <% unless current_user %>
        <li class="nav-item active">
          <%= link_to 'Log In', login_path, class: "nav-link", data: {target: "#LoginModal", toggle: 'modal'} %>
        </li>
        <li class="nav-item active">
          <%= link_to 'Register', new_user_path, class: "nav-link", data: {target: "#RegisterModal", toggle: 'modal'} %>
        </li>
        <% end %>

        <li class="nav-item">
          <%= content_tag(:span, "Hi, #{current_user.first_name}!", class: "nav-link") if current_user %>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Where to?
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="/users/account_profile">Account Profile</a>
            <a class="dropdown-item" href="/buildbox">Build-A-BeachBox</a>
            <a class="dropdown-item" href=""><%= link_to 'Log Out', logout_path, method: :delete, class: "nav-link"%></a>
          </div>
        </ul>

        <form class="form-inline my-2 my-lg-0">
        </form>
      </div>
    </nav>

    <%= yield %>
    <%= render partial: "users/footer" %>
    <%= render partial: 'users/login_modal' %>
    <%= render partial: 'users/register_modal' %>
    
  </body>

  </html>

app/views/layouts/charges.html.erb
<!DOCTYPE html>
<html>
  <head></head>
  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/_panel1.html.erb
<div class="card-header" id="headingOne" >
  <div class="panel-heading" >
    <h4 class="panel-title" >
      <div data-toggle="" aria-expanded="true" aria-controls="collapseOne">
        Who is going to the beach?
      </div>
    </h4>
  </div>
 <div id="collapseOne" class="collapse show" aria-labelledby="headingOne" data-parent="#accordion">
   <div class="card-body" id="collapse1">
      <button type="button" class="btn btn-warning btn-lg btn-block" id="box_family">Family</button>
      <button type="button" class="btn btn-outline-warning btn-lg btn-block" id="box_adult">Only Adults</button>
    </div>
  </div>
</div>

app/views/pages/_panel2.html.erb
<div class="card-header" id="headingTwo">
  <h4 class="panel-title" >
    <div data-toggle="" aria-expanded="true" aria-controls="collapseTwo">
      How many people?</div>
    </h4>
  </div>

  <!-- Panel 2 body -->
  <div id="collapse2" class="collapse" aria-labelledby="headingTwo" data-parent="#accordion">
    <div class="card-body" >

      <div class="form-group">
        <br>
        <div class="counter-adult">

          <div class="control-label"><strong>Adult</strong> <i> (above 13)</i></div>
          <br>

          <div class="counter"><div class="input-group number-spinner">

            <span class="input-group-btn">
              <a class="btn btn-outline-info" data-dir="dwn"><i class="fas fa-minus"></i></a>
            </span>

            <input type="text" disabled name="adult" id="adult" class="form-control text-center" value="1" max=9 min=1>

            <span class="input-group-btn">
              <a class="btn btn-info" data-dir="up"><i class="fas fa-plus"></i></a>
            </span>

            </div>

          </div>

          <br><br>
        </div>




        <br>
        <div class="counter-child">
          <br>
          <div class="control-label"><strong>Child</strong><i> (1 - 13)</i></div>
          <br>
          <div class="counter"><div class="input-group number-spinner">
            <span class="input-group-btn">
              <a class="btn btn-outline-info" data-dir="dwn"><i class="fas fa-minus"></i></a>
            </span>
            <input type="text" disabled name="child" id="child" class="form-control text-center" value="0" max=9 min=0>
            <span class="input-group-btn">
              <a class="btn btn-info" data-dir="up"><i class="fas fa-plus"></i></a>
            </div>
          </div>
        </div>


        <br>
        <br>
        <br>
        <div class="buttons-p2">

          <span data-tooltip="  Changes will be lost."><button type="button" class="btn btn-warning" id="back-to-1">Back</button></span>
          <button type="button" class="btn btn-outline-warning" id="entered-quantity" value='hide/show'>Next</button>
        </div>
      </div>
    </div>
  </div>

app/views/pages/_panel3.html.erb
<div class="card-header" id="headingThree">
  <h4 class="panel-title">
    <div data-toggle="" aria-expanded="true" aria-controls="collapseTwo">
      Here's what you need...</div>
    </h4>
  </div>

  <!-- Panel 3 body -->
  <div  class="collapse" aria-labelledby="headingThree" data-parent="#accordion" id="collapse3">
    <div class="card-body">
      <div class="product-list">
        <% @products.each do |product| %>
        <%= render "product_row", product: product, order_item: @order_item %>
        <% end %>
      </div>      

    </div>
    <span data-tooltip="  Changes will be lost.">
      <button type="button" class="btn btn-warning" id="back-to-2">Back</button>
    </span>
    <%= link_to '<button type="button" class="btn btn-outline-warning cart-update">Next</button>'.html_safe, '/delivery' %>
  </div>

app/views/pages/_panel4.html.erb
<div class="panel panel-default" >
  <div class="panel-heading" >

    <h4 class="panel-title">
      <div data-toggle="" data-parent="#accordion" href="#collapse2">
        How many people?</div>
      </h4>

    </div>
    
    <!-- Panel 2 body -->
    <div id="collapse4" class="panel-collapse collapse" >
      <div class="panel-body" >
        Hello

      </div>
    </div>
  </div>

app/views/pages/_product_row.html.erb
<% p_name = product.product_name.parameterize.underscore %>
<div class="productphotos <%= p_name %>" data-target="<%= p_name %>"><%= image_tag(product.product_image_url) %>
  <br>
  <div class="form-group">
    <div class="control-label"><%= product.product_name %></div>
    <label class="control-label2">$<%= product.product_price %> (unit price)</label>
    <br>
    <p></p>
    <div class="input-group number-spinner">
      <span class="input-group-btn">
              <a class="btn btn-outline-info spin" data-dir="dwn"><i class="fas fa-minus"></i></a>
      </span>
      <input type="text" disabled data-id="<%= product.id %>" data-name="<%= product.product_name %>" name="<%= p_name %>_qty" id="<%= p_name %>_qty" class="form-control text-center item_qty" value="1" max=9 min=1>
      <span class="input-group-btn">
        <a class="btn btn-info" data-dir="up"><i class="fas fa-plus"></i></a>
      </span>
    </div>
  </div>
</div>

app/views/pages/delivery.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
<head>

  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <title>BuildBox</title>
</head>
<body>

  <div class="stepper">

    <div class="stepper-step stepper-step-isValid">
      <div class="stepper-stepContent">
        <span class="stepper-stepMarker">1</span>Build Your Box
      </div>
    </div>
    <div class="stepper-step stepper-step-isActive">
      <div class="stepper-stepContent">
        <span class="stepper-stepMarker">2</span>Delivery
      </div>
    </div>
    <div class="stepper-step stepper-step-isActive">
      <div class="stepper-stepContent">
        <span class="stepper-stepMarker">3</span>Checkout
      </div>
    </div>
  </div>

<h1>Delivery Details</h1>

<div id="delivery-content">
  <div class="delivery-content"></div>
    <div id="out">
    <p><button class="btn btn-outline-info" onclick="geoFindMe()" id=#button5>Use my current location</button></p>
    </div>
    <div class="google_map">
      <div id="map"></div>
    </div>

<div id="addressinputs">
        <form action = "cart/update" method="post">

              <div id="enteraddress"><font color="white"><strong>Or, enter your address:</strong></font></div>
              <br>
              <input type="text"  id="geoaddress" name="street_address" required placeholder="ex. 549, NW 28th St, Miami, FL"/>
              <br>
              <br>
              <input class="btn btn-outline-info" type="submit" value="Confirm Address & Checkout"/>
            </form>
      </div>
      <br>
      <br>
      <br>
      <div class="delivery-back-btn">
        <%= link_to '<button type="button" class="btn btn-warning" id="backtobuild">Back to Build-A-BeachBox</button>'.html_safe, '/buildbox' %>
      </div>
</div>
  </body>

</html>

app/views/pages/index.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
<head>

  <script defer src="https://use.fontawesome.com/releases/v5.0.13/js/all.js" integrity="sha384-xymdQtn1n3lH2wcu0qhcdaOpQwyoarkgLVxC/wZ5q7h9gHtxICrpcaSUfygqZGOe" crossorigin="anonymous"></script>

  <meta charset= "utf-8">
  <title>BuildBox</title>

</head>
<body>



  <div class="stepper">

    <div class="stepper-step stepper-step-isValid">
      <div class="stepper-stepContent">
        <span class="stepper-stepMarker">1</span>Build Your Box
      </div>
    </div>
    <div class="stepper-step stepper-step-isActive">
      <div class="stepper-stepContent">
        <span class="stepper-stepMarker">2</span>Delivery
      </div>
    </div>
    <div class="stepper-step stepper-step-isActive">
      <div class="stepper-stepContent">
        <span class="stepper-stepMarker">3</span>Checkout
      </div>
    </div>
  </div>


  <div id="stepper-content">
    <div id="accordion1">

      <div class="card" id="accordion">

        <!-- ACCORDION PANEL 1 (family/adults)-->
        <%= render 'panel1' %>

        <!-- ACCORDION PANEL 2 (# people) -->
        <%= render 'panel2' %>

        <!-- ACCORDION PANEL 3 (cart) -->
        <%= render 'panel3' %>


      </div>

    </div>

  </div>






</body>

</html>

app/views/pages/thanks.html.erb
    <h2>Thank you for purchasing your BeachBox, please check your email for delivery updates.</h2>
    <h2>Your box will be ready soon</h2>